apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "3"
    persistentvolumeclaims: "4"
    pods: "2"
    replicationcontrollers: "10"
    secrets: "10"
    services: "5"
    services.loadbalancers: "2"