apiVersion: v1
kind: Service
metadata:
  name: local-pv-demo-app
spec:
  selector:
    app: my-local-pv-demo-app
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      #옵션 설정을 하지 않으면 클러스터 설정의 할당포트대역 내에서 자동으로 할당
      #nodePort: 30009
