apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-bootcamp-yaml
  namespace: msaclass-a
spec:
  containers:
  - name: kubernetes-bootcamp
    image: jocatalin/kubernetes-bootcamp:v1
    ports:
    - containerPort: 8080
    
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-bootcamp-yaml
  namespace: msaclass-b
spec:
  containers:
  - name: kubernetes-bootcamp
    image: jocatalin/kubernetes-bootcamp:v1
    ports:
    - containerPort: 8080