apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: msaclass-user
  namespace: msaclass
rules:
  - apiGroups:
      - ""            # core api
      - "extensions"
      - "apps"
    resources:
      - "deployments"
      - "replicasets"
      - "pods"
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"