apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: msaclass-user-rolebinding
  namespace: msaclass
subjects:
  - kind: User         # User or ServiceAccount
    name: msaclass
roleRef:
  kind: Role
  name: msaclass-user
  apiGroup: rbac.authorization.k8s.io