apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: spring-cloud
data:
  # if you want to deploy n instances of eureka cluster, 
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka
  eureka_service_address: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka,http://eureka-2.eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: spring-cloud
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    name: eureka
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: spring-cloud
spec:
  serviceName: 'eureka'
  # n instances
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: chupdachups/spring-cloud-eureka:k8s
        ports:
        - containerPort: 8761
#        resources:
#          requests:
#            memory: "1Gi"
#            cpu: "500m"
#          limits:
#            memory: "1200Mi"
#            cpu: "500m"
        env:
        - name: eureka-servers
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
        - name: profile
          value: docker
        - name: service_port
          value: "8761"
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: eureka
  namespace: spring-cloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: myeureka.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eureka
            port:
              number: 8761