apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-secret-app-deployment
  labels:
    app: k8s-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-secret-app
  template:
    metadata:
      labels:
        app: k8s-secret-app
    spec:
      containers:
      - name: k8s-secret-app
        image: chupdachups/k8s-config-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_MESSAGE
          valueFrom:
            secretKeyRef: 
              name: secret-message
              key: config-message
              
---
apiVersion: v1
kind: Service
metadata:
  name: secret-app-svc
  labels:
    app: k8s-secret-app
spec:
  type: NodePort
  selector:
    app: k8s-secret-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080