apiVersion: v1
kind: Service
metadata:
  name: my-bootcamp-nodeport-svc
spec:
  type: NodePort
  selector:
    app: my-bootcamp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      #옵션 설정을 하지 않으면 클러스터 설정의 할당포트대역 내에서 자동으로 할당
      #nodePort: 30009
      